name: Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  feeds:
    runs-on: ubuntu-latest
    name: Build static feeds site
    steps:
      - name: Run Action
        uses: llun/feeds@2.6.4
        with:
          storageType: files
          # customDomain: feeds.llun.dev
